name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SFML
        run: |
          sudo apt-get update
          sudo apt-get install libsfml-dev

      - name: Compile
        run: |
          mkdir -p build
         g++ -Wall -o build/TicTacToe_game src/main.cpp -I. -lsfml-graphics -lsfml-window -lsfml-system

      - name: Run program
        run: |
          ./build/TicTacToe_game
